from jinja2 import Template
from datetime import datetime
from typing import List, Dict

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: 'Inter', -apple-system, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background: #0f172a; color: #f8fafc; padding: 40px; border-radius: 12px; text-align: center; margin-bottom: 40px; }
    .header h1 { margin: 0; font-size: 28px; letter-spacing: -0.02em; }
    .header p { margin: 10px 0 0; opacity: 0.8; font-style: italic; }
    .section { background: #ffffff; border: 1px solid #e2e8f0; padding: 30px; border-radius: 12px; margin-bottom: 30px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
    .section-title { color: #2563eb; font-weight: 700; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 10px; }
    .video-title { font-size: 22px; font-weight: 800; margin-top: 0; margin-bottom: 15px; color: #0f172a; }
    .core-thesis { font-weight: 600; font-style: italic; color: #475569; border-left: 4px solid #cbd5e1; padding-left: 15px; margin-bottom: 20px; }
    .bullet-list { padding-left: 20px; margin-bottom: 20px; }
    .bullet-list li { margin-bottom: 8px; }
    .tag { display: inline-block; background: #f1f5f9; color: #475569; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: 600; margin-right: 5px; margin-bottom: 5px; }
    .action-box { background: #f0fdf4; border: 1px solid #bbf7d0; padding: 20px; border-radius: 8px; margin-top: 20px; }
    .action-title { color: #166534; font-weight: 700; font-size: 14px; text-transform: uppercase; margin-bottom: 5px; }
    .footer { text-align: center; color: #64748b; font-size: 12px; margin-top: 50px; }
    a { color: #2563eb; text-decoration: none; font-weight: 600; }
    a:hover { text-decoration: underline; }
</style>
</head>
<body>
    <div class="header">
        <h1>Weekly Intelligence Digest</h1>
        <p>{{ date }} • Strategic Triage: Writing, Productivity, AI Agents</p>
    </div>

    {% for item in analyses %}
    <div class="section">
        <div class="section-title">{{ item.video.niche }} • {{ item.video.uploader }}</div>
        <h2 class="video-title"><a href="{{ item.video.url }}">{{ item.video.title }}</a></h2>
        
        <div class="core-thesis">{{ item.analysis.core_thesis }}</div>
        
        <div class="section-title">Key Insights</div>
        <ul class="bullet-list">
            {% for arg in item.analysis.key_arguments %}
            <li>{{ arg }}</li>
            {% endfor %}
        </ul>

        <div>
            {% for model in item.analysis.mental_models %}
            <span class="tag">{{ model }}</span>
            {% endfor %}
        </div>

        <div class="action-box">
            <div class="action-title">Actionable Task</div>
            <p>{{ item.analysis.actionable_task }}</p>
        </div>
        
        <p style="margin-top: 20px; font-size: 14px; color: #64748b;"><strong>TELOS Alignment:</strong> {{ item.analysis.telos_alignment }}</p>
    </div>
    {% endfor %}

    <div class="footer">
        Generated by Gemini CLI • TELOS Mission Control • Obsidian Vault Studio
    </div>
</body>
</html>
"""

class DigestFormatter:
    def format(self, results: List[Dict]) -> str:
        template = Template(HTML_TEMPLATE)
        return template.render(
            date=datetime.now().strftime("%B %d, %Y"),
            analyses=results
        )

if __name__ == "__main__":
    pass
